server:
    port: 8090
spring:
  application:
    name: dynata-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: task
    password: task
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
          time_zone: UTC
          batch_size : 1000
        order_inserts: true
#        order_updates: true
#        generate_statistics: true
        default_schema: dynata
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: dynata
    schemas:
      - dynata
    create-schemas: true
management:
  endpoints:
    web:
      exposure:
        include:
          "*"
mybatis:
  mapperLocations: classpath*:**/*Mapper.xml
initDataList:
  - static/initData/OO - 2 - Statuses.csv
  - static/initData/OO - 2 - Members.csv
  - static/initData/OO - 2 - Surveys.csv
  - static/initData/OO - 2 - Participation.csv