CREATE SEQUENCE participation_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE member_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE status_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE survey_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE PARTICIPATION
(
    ID           BIGINT     NOT NULL,
    MEMBER_ID    BIGINT     NOT NULL,
    SURVEY_ID    BIGINT     NOT NULL,
    STATUS_ID    BIGINT     NOT NULL,
    LENGTH       BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE MEMBER
(
    ID                  BIGINT        NOT NULL,
    FULL_NAME           VARCHAR(400)  NOT NULL,
    EMAIL_ADDRESS       VARCHAR(400)  NOT NULL,
    IS_ACTIVE           BIGINT        NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STATUS
(
    ID                  BIGINT        NOT NULL,
    NAME                VARCHAR(400)  NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SURVEY
(
    ID                   BIGINT        NOT NULL,
    NAME                 VARCHAR(400)  NOT NULL,
    EXPECTED_COMPLETES   BIGINT        NOT NULL,
    EXPECTED_POINTS      BIGINT        NOT NULL,
    FILTERED_POINTS      BIGINT        NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE PARTICIPATION
    ADD CONSTRAINT FK_PARTICIPATION_MEMBER_ID
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER;

ALTER TABLE PARTICIPATION
    ADD CONSTRAINT FK_PARTICIPATION_STATUS_ID
        FOREIGN KEY (STATUS_ID) REFERENCES STATUS;

ALTER TABLE PARTICIPATION
    ADD CONSTRAINT FK_PARTICIPATION_SURVEY_ID
        FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY;